version: "3.7"
services:
  app:
    image: gotodo
    build:
      context: .
      target: dev
    environment:
      TODO_ENV: dev
      PORT: 8080
    volumes:
      - .:/app
    ports:
      - "18000:8080"
